### ISSUE TITLE
Tutorial [apresentação] maven 

### ISSUE THREAD

**Issue by fpenha** [fpenha/GASP-BPM#2]
Tutorial [apresentação] prático sobre o uso da ferramenta maven, compreendo os seus benefícios. Os exemplos práticos deverá ser mostrando dentro e fora do ambiente eclipse.

Para ajudar:
Instalar/configurar o Maven
Configurar o Maven no eclipse
Criar um projeto Maven
Configurar o POM
Estrutura de diretório padrão
Repositório

**Comment by marciodouglasIFRN** [comment]
Apresentação/Tutorial, sobre a ferramenta maven, concluída.

**Comment by marciodouglasIFRN** [comment]
Apresentação/Tutorial, sobre a ferramenta maven, concluída.
