### ISSUE TITLE
Prototipação de Login e Paletas de Cores

### ISSUE THREAD

**Issue by fpenha** [fpenha/GASP-BPM#3]
Projetar a prototipação da tela de login. Para esta atividade, pense em alguma ferramenta mais adequada ( sugestão: https://pencil.evolus.vn/ ) e, durante o processo, vejam esta ferramenta para auxiliar na "combinação" de cores ( https://color.adobe.com/pt/create/color-wheel/ ), por enquanto, esqueça um um pouco a relação das cores e a psicologia, vamos nos preocupar com a harmonia.

Curiosidade : Como moldar o nosso desenvolvimento/prototipação ao Design Thinking ??
Para depois : Vá pensando em uma tela dashboard para uma segunda tela, logo depois de Login.
Para utilizar https://color.adobe.com/pt/create/color-wheel/ : busque entender os tipos de harmonia

**Comment by AlexiaTuane** [comment]
concluido
